services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prontoatendimento_db
      MYSQL_USER: prontoatendimento
      MYSQL_PASSWORD: prontoatendimento
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: