name: 🚀 Deploy via ftp
on: 
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        protocol: ftps-legacy
        port: 22
        local-dir: "./"
        server-dir: "./prontoatendimento/"
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
